name: cs224n-final-proj
# Run 
# mamba env update --file environment.yaml 
# to install the packages.
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  # for data analysis
  - pandas
  - numpy
  - matplotlib
  # for model
  - pytorch 
  - transformers
  - datasets
  # - bitsandbytes
  # - accelerate
  # - sentencepiece
  # for jupyter notebook
  - jupyter
  - ipykernel
  - ipywidgets
  - widgetsnbextension
  - pandas-profiling
  # for wandb
  - wandb
